### ISSUE TITLE
[Error Report]: Mod Manager Crashes when attempting to point it to vanilla SA2 install without a `/mods` folder.

### ISSUE THREAD

**Issue by PoryGone** [X-Hax/SA-Mod-Manager#100]
If you point the Mod Manager at an SA2 install folder that does not contain a `/mods` folder already, it will crash and fail to install 100% of the time. If you manually create a `/mods` folder, it will not crash, and will successfully install.

## Exception Report
```
SAMM Information:
	Manager Version: 1.2.5
	Current Game: Sonic Adventure 2
	Game Directory: D:\Games\SteamLibrary\steamapps\common\Sonic Adventure 2
	Manager Location: D:\Games\
	Running as Admin: False
	Mod Loader Version (Hash): 3880a0e2a38f29323c44430a496891c0f64ac620
```

```
Exception Information:
	Type: DirectoryNotFoundException
	Exception: Could not find a part of the path 'D:\Games\SteamLibrary\steamapps\common\Sonic Adventure 2\mods'.
	Source: System.Private.CoreLib
	In Function: IntPtr CreateDirectoryHandle(System.String, Boolean)
	StackTrace:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
	   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
	   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
	   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
	   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
	   at SAModManager.Profile.ProfileManager.MigrateProfiles(Boolean deletesource)
	   at SAModManager.Profile.ProfileManager.CreateProfiles()
	   at SAModManager.MainWindow.Load(Boolean newSetup)
	   at SAModManager.MainWindow.DoGameSwap(String newPath)
	   at SAModManager.MainWindow.ResultPickGame(String path)
	   at SAModManager.MainWindow.btnBrowseGameDir_Click(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by Sora-yx** [comment]
This should be fixed with the last update
