### ISSUE TITLE
[Error Report]:Opened my SA Mod Manager and saw this. What do i do?

### ISSUE THREAD

**Issue by Chevroney** [X-Hax/SA-Mod-Manager#101]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.6
	Current Game: Sonic Adventure 2
	Game Directory: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2
	Manager Location: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure DX\
	Running as Admin: True
```

```
Exception Information:
	Exception: INI File error: Value "DLLFile" already exists in group "".
line 7
	Source: SAModManager
	In Function: System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,System.String]] Load(System.String[])
	StackTrace:    at SAModManager.Ini.IniFile.Load(String[] data)
	   at SAModManager.Ini.IniFile.Load(String filename)
	   at SAModManager.Ini.IniSerializer.Deserialize[T](String filename)
	   at SAModManager.MainWindow.LoadModList()
	   at SAModManager.MainWindow.Load(Boolean newSetup)
	   at SAModManager.MainWindow.MainWindowManager_Loaded(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
	InnerException: System.ArgumentException: An item with the same key has already been added. Key: DLLFile
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SAModManager.Ini.IniFile.Load(String[] data)
```

**Comment by Sora-yx** [comment]
One of your mod has the value **DLLFile** twice in its **mod.ini**, you need to find it and remove it from the ini file.

**Comment by ItsEasyActually** [comment]
If you happen to figure out which mod it is, please let us know and also report it to the mod author for them to fix. This is actually the second report we've seen about this, but nobody has figured out what mod it is.

**Comment by Chevroney** [comment]
After an hour, I finally found the mod who broke the Mod Manager and it's this one: https://gamebanana.com/mods/245229 Thank you so much for y'all help and keep up the good work for y'all mods they are a game changer and makes an amazing game an even better game!

**Comment by Sora-yx** [comment]
Cool thanks for telling us the name, this looks like an issue that has been there for years, best to contact [GBA64](https://gamebanana.com/members/1531491) to fix this.

**Comment by PiKeyAr** [comment]
Maybe the INI serializer thing could be wrapped in try-catch, and on error it could display the invalid mod name with a Yes/No dialog to let the user uninstall it?
