### ISSUE TITLE
[Error Report]: Mod Manager crash when game folder is moved to a different drive

### ISSUE THREAD

**Issue by ChrisFratz** [X-Hax/SA-Mod-Manager#103]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.6
	Current Game: Sonic Adventure DX
	Game Directory: G:\SteamLibrary\steamapps\common\Sonic Adventure DX
	Manager Location: E:\SteamLibrary\steamapps\common\Sonic Adventure DX\
	Running as Admin: False
	Mod Loader Version (Hash): d1ca53641859529ce005acb5d8a1b984ce02fe48
```

```
Exception Information:
	Type: IOException
	Exception: The device is not ready. : 'G:\SteamLibrary\steamapps\common\Sonic Adventure DX\mods'
	Source: System.Private.CoreLib
	In Function: IntPtr CreateDirectoryHandle(System.String, Boolean)
	StackTrace:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
	   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
	   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
	   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
	   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
	   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, EnumerationOptions enumerationOptions)
	   at SAModManager.SAModInfo.GetModFiles(DirectoryInfo directoryInfo)+MoveNext()
	   at SAModManager.MainWindow.LoadModList()
	   at SAModManager.MainWindow.Refresh()
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

I haven't loaded up anything from SA1 in a while, and now the mod manager is crashing. IDK what to do other than report it.

**Comment by PiKeyAr** [comment]
Does your G drive actually exist when it happens? It seems like it can't access the game path because the device isn't available. Is your game on an external drive that has a different drive letter now? We should probably add some kind of workaround for cases like this, but at the moment you might have to restore the original drive letter (and also path if you've moved the game) to be able to run the Mod Manager. 

You could also go to `%localappdata%\SAManager\SADX` and edit the file `Default.json` (or whichever profile name you had) and fix the `GamePath` variable at the bottom to use a different path, or delete the whole `SAManager` folder to reset all Manager settings.

**Comment by ChrisFratz** [comment]
I changed up the drive letter in the Json file and now it works again. Thanks for the note.

**Comment by Sora-yx** [comment]
With the Last Update it should no longer crash when moving the game to a different folder.
