### ISSUE TITLE
[Error Report]:

### ISSUE THREAD

**Issue by galva12** [X-Hax/SA-Mod-Manager#122]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.8
	Current Game: Sonic Adventure DX
	Game Directory: C:\Program Files (x86)\Sonic Adventure DX
	Manager Location: C:\Users\user\Desktop\
	Running as Admin: False
```

```
Exception Information:
	Type: UnauthorizedAccessException
	Exception: Access to the path 'C:\Program Files (x86)\Sonic Adventure DX\mods' is denied.
	Source: System.Private.CoreLib
	In Function: Void CreateDirectory(System.String, Byte[])
	StackTrace:    at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
	   at System.IO.Directory.CreateDirectory(String path)
	   at SAModManager.Profile.ProfileManager.MigrateProfiles(Boolean deletesource)
	   at SAModManager.Profile.ProfileManager.CreateProfiles()
	   at SAModManager.MainWindow.Load(Boolean newSetup)
	   at SAModManager.MainWindow.DoGameSwap(String newPath)
	   at SAModManager.MainWindow.ResultPickGame(String path)
	   at SAModManager.MainWindow.btnBrowseGameDir_Click(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
	   at System.Windows.Threading.Dispatcher.Run()
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at System.Windows.Application.Run()
	   at SAModManager.App.Main()
```

**Comment by Sora-yx** [comment]
As the error mentions, this is a perm issue, running it as admin should fix your issue.
