### ISSUE TITLE
[Error Report]: Windows Defender sees Mod manager as virus and cannot be updated,

### ISSUE THREAD

**Issue by danielzx2** [X-Hax/SA-Mod-Manager#123]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.6
	Current Game: Sonic Adventure 2
	Game Directory: G:\SteamLibrary\steamapps\common\Sonic Adventure 2
	Manager Location: E:\Mods\Sonic Adventure Mod Loader\
	Running as Admin: False
	Mod Loader Version (Hash): ce3cf47093922bc32786149c6740825bf6f25253
```

```
Exception Information:
	Type: Win32Exception
	Exception: An error occurred trying to start process 'E:\Mods\Sonic Adventure Mod Loader\.SATemp\SAModManager.exe' with working directory 'E:\Mods\Sonic Adventure Mod Loader'. Operation did not complete successfully because the file contains a virus or potentially unwanted software.
	Source: System.Diagnostics.Process
	In Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
	StackTrace:    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
	   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
	   at SAModManager.Updater.ManagerUpdate.DownloadManagerCompleted(String tempFolderPath, String fileName)
	   at SAModManager.App.<>c__DisplayClass52_0.<<PerformUpdateManagerCheck>b__0>d.MoveNext()
	--- End of stack trace from previous location ---
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by ItsEasyActually** [comment]
Create an exception for it in Windows Defender. False positives with AV software is extremely common and we don't have much control over that.

**Comment by danielzx2** [comment]
That's how I solved it now
