### ISSUE TITLE
[Error Report]:

### ISSUE THREAD

**Issue by Henry-A-S** [X-Hax/SA-Mod-Manager#127]
i was just trying to mod sadx and mod manager keeps crashing
 i just opened it, then it updated, and told me to delete mod.ini in the mods folder, and so i did, and now it's not working :(

## Exception Report
```
SAMM Information:
	Manager Version: 1.2.8
	Current Game: Sonic Adventure DX
	Game Directory: C:\\Program Files (x86)\\Steam\steamapps\common\Sonic Adventure DX
	Manager Location: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure DX\
	Running as Admin: False
	Mod Loader Version (Hash): 9d6cbe913322052c2ecee5a4beaa42525eb96fb3
```

```
Exception Information:
	Type: ArgumentOutOfRangeException
	Exception: startIndex cannot be larger than length of string. (Parameter 'startIndex')
	Source: System.Private.CoreLib
	In Function: Void ThrowSubstringArgumentOutOfRange(Int32, Int32)
	StackTrace:    at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
	   at System.String.Substring(Int32 startIndex, Int32 length)
	   at SAModManager.MainWindow.LoadModList()
	   at SAModManager.MainWindow.Load(Boolean newSetup)
	   at SAModManager.MainWindow.MainWindowManager_Loaded(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

```
{
  "SettingsVersion": 1,
  "CurrentSetGame": 1,
  "Theme": 0,
  "Language": 0,
  "ModAuthor": "",
  "EnableDeveloperMode": true,
  "KeepManagerOpen": true,
  "UpdateSettings": {
    "EnableManagerBootCheck": true,
    "EnableModsBootCheck": true,
    "EnableLoaderBootCheck": true,
    "UpdateTimeOutCD": 133588083604245566,
    "UpdateCheckCount": 2
  },
  "gamesInstalled": [
    1
  ]
}
```
```
{
  "SettingsVersion": 2,
  "Graphics": {
    "SelectedScreen": 1,
    "HorizontalResolution": 1920,
    "VerticalResolution": 1080,
    "Enable43ResolutionRatio": false,
    "EnableVsync": true,
    "EnablePauseOnInactive": true,
    "CustomWindowWidth": 640,
    "CustomWindowHeight": 480,
    "EnableKeepResolutionRatio": false,
    "EnableResizableWindow": false,
    "FillModeBackground": 2,
    "FillModeFMV": 2,
    "ModeTextureFiltering": 0,
    "ModeUIFiltering": 0,
    "EnableUIScaling": true,
    "EnableForcedMipmapping": true,
    "EnableForcedTextureFilter": true,
    "ScreenMode": 2,
    "GameFrameRate": 0,
    "GameFogMode": 0,
    "GameClipLevel": 0,
    "ShowMouseInFullscreen": false,
    "EnableCustomWindow": false,
    "EnableBorderless": true,
    "EnableScreenScaling": true
  },
  "Controller": {
    "EnabledInputMod": true,
    "VanillaMouseUseDrag": false,
    "VanillaMouseStart": 0,
    "VanillaMouseAttack": 0,
    "VanillaMouseJump": 0,
    "VanillaMouseAction": 0,
    "VanillaMouseFlute": 0
  },
  "Sound": {
    "EnableGameMusic": true,
    "EnableGameSound": true,
    "EnableGameSound3D": true,
    "EnableBassMusic": true,
    "EnableBassSFX": true,
    "GameMusicVolume": 100,
    "GameSoundVolume": 100,
    "SEVolume": 100
  },
  "TestSpawn": {
    "UseCharacter": false,
    "UseLevel": false,
    "UseEvent": false,
    "UseGameMode": false,
    "UseSave": false,
    "LevelIndex": -1,
    "ActIndex": 0,
    "CharacterIndex": -1,
    "EventIndex": -1,
    "GameModeIndex": -1,
    "SaveIndex": -1,
    "GameTextLanguage": 1,
    "GameVoiceLanguage": 1,
    "UseManual": false,
    "UsePosition": false,
    "XPosition": 0,
    "YPosition": 0,
    "ZPosition": 0,
    "Rotation": 0
  },
  "Patches": {
    "HRTFSound": true,
    "KeepCamSettings": true,
    "FixVertexColorRendering": true,
    "MaterialColorFix": true,
    "NodeLimit": true,
    "FOVFix": true,
    "SkyChaseResolutionFix": true,
    "Chaos2CrashFix": true,
    "ChunkSpecularFix": true,
    "E102NGonFix": true,
    "ChaoPanelFix": true,
    "PixelOffSetFix": true,
    "LightFix": true,
    "KillGBIX": true,
    "DisableCDCheck": false,
    "ExtendedSaveSupport": true,
    "CrashGuard": true
  },
  "DebugSettings": {
    "EnableDebugConsole": false,
    "EnableDebugScreen": false,
    "EnableDebugFile": false,
    "EnableDebugCrashLog": true,
    "EnableShowConsole": null
  },
  "GamePath": "C:\\\\Program Files (x86)\\\\Steam\\steamapps\\common\\Sonic Adventure DX",
  "EnabledMods": [],
  "EnabledCodes": []
}
```

**Comment by Sora-yx** [comment]
Looking at your settings, it looks like the game path is wrong as it has four backslashes. 
I'd recommend going in appdata -> local and remove the folder SAManager to reset the settings.
