### ISSUE TITLE
[Error Report]:

### ISSUE THREAD

**Issue by ShadeDergon197** [X-Hax/SA-Mod-Manager#129]
Tried to install a mod from gamebanana, and it gave me this error.

## Exception Report
```
SAMM Information:
	Manager Version: 1.2.8
	Current Game: Sonic Adventure 2
	Game Directory: E:\SteamLibrary\steamapps\common\Sonic Adventure 2
	Manager Location: E:\SteamLibrary\steamapps\common\Sonic Adventure 2\
	Running as Admin: False
	Mod Loader Version (Hash): 7e472d7453bf152c91e49398ec0f867b4c689702
```

```
Exception Information:
	Exception: Failed to install one mod.
	Source: SAModManager
	In Function: Void MoveNext()
	StackTrace:    at SAModManager.InstallModOptions.InstallModOptionsArchive(String[] path, String root)
	   at SAModManager.InstallModOptions.InstallMod(String[] path, String root)
	   at SAModManager.MainWindow.NewModBtn_Click(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

```
{
  "SettingsVersion": 1,
  "CurrentSetGame": 2,
  "Theme": 0,
  "Language": 0,
  "ModAuthor": "",
  "EnableDeveloperMode": false,
  "KeepManagerOpen": true,
  "UpdateSettings": {
    "EnableManagerBootCheck": true,
    "EnableModsBootCheck": true,
    "EnableLoaderBootCheck": true,
    "UpdateTimeOutCD": 0,
    "UpdateCheckCount": 1
  },
  "gamesInstalled": [
    2,
    1
  ]
}
```
```
{
  "SettingsVersion": 1,
  "Graphics": {
    "SelectedScreen": 1,
    "HorizontalResolution": 640,
    "VerticalResolution": 480,
    "EnablePauseOnInactive": false,
    "CustomWindowWidth": 640,
    "CustomWindowHeight": 480,
    "EnableKeepResolutionRatio": false,
    "EnableResizableWindow": false,
    "ScreenMode": 1,
    "KeepAspectWhenResizing": false,
    "GameTextLanguage": 0,
    "SkipIntro": false
  },
  "TestSpawn": {
    "UseCharacter": false,
    "UsePlayer2": false,
    "UseLevel": false,
    "UseEvent": false,
    "UseSave": false,
    "LevelIndex": -1,
    "MissionIndex": 0,
    "CharacterIndex": -1,
    "Player2Index": -1,
    "EventIndex": -1,
    "SaveIndex": -1,
    "GameTextLanguage": 0,
    "GameVoiceLanguage": 1,
    "UseManual": false,
    "UsePosition": false,
    "XPosition": 0,
    "YPosition": 0,
    "ZPosition": 0,
    "Rotation": 0
  },
  "Patches": {
    "FramerateLimiter": true,
    "DisableExitPrompt": true,
    "SyncLoad": true,
    "ExtendVertexBuffer": true,
    "EnvMapFix": true,
    "ScreenFadeFix": true,
    "CECarFix": true,
    "ParticlesFix": true
  },
  "DebugSettings": {
    "EnableDebugConsole": false,
    "EnableDebugScreen": false,
    "EnableDebugFile": false,
    "EnableDebugCrashLog": true,
    "EnableShowConsole": null
  },
  "GamePath": "E:\\SteamLibrary\\steamapps\\common\\Sonic Adventure 2",
  "EnabledMods": [
    "FreeCamV3",
    "PhysicsSwap",
    "SA2CharSel",
  ],
  "EnabledCodes": [
    "Infinite Lives P1",
    "Have Invincibility",
    "Press Pause Key to Freeze Time",
    "Gold Beetle Never Disappears",
    "All emeralds trackable in treasure hunt stages"
  ]
}
```

**Comment by Sora-yx** [comment]
What mod?

**Comment by Sora-yx** [comment]
Next update will have a failsafe and tell which mod crashed, until then, feel free to re open this if you want to share that mod.
