### ISSUE TITLE
[Error Report]: Mod Manager crashing during startup

### ISSUE THREAD

**Issue by TJdafish** [X-Hax/SA-Mod-Manager#130]
It just started crashing when i open it. It was working fine 20 minutes ago, only think i can think of is me opening it while i was in game! please help!

## Exception Report
```
SAMM Information:
	Manager Version: 1.2.8
	Current Game: Sonic Adventure 2
	Game Directory: D:\SteamLibrary\steamapps\common\Sonic Adventure 2
	Manager Location: D:\SteamLibrary\steamapps\common\Sonic Adventure DX\
	Running as Admin: False
	Mod Loader Version (Hash): ce3cf47093922bc32786149c6740825bf6f25253
```

```
Exception Information:
	Type: IOException
	Exception: The process cannot access the file 'D:\SteamLibrary\steamapps\common\Sonic Adventure 2\resource\gd_PC\DLL\Win32\Data_DLL.dll' because it is being used by another process.
	Source: System.Private.CoreLib
	In Function: Void CopyFile(System.String, System.String, Boolean)
	StackTrace:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
	   at SAModManager.MainWindow.ManualLoaderUpdateCheck()
	   at SAModManager.MainWindow.Load(Boolean newSetup)
	   at SAModManager.MainWindow.MainWindowManager_Loaded(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by Sora-yx** [comment]
As the error says, this was crashing due to the dll being used when playing the game, this should be fixed with the last Manager update.
