### ISSUE TITLE
[Error Report]: INI File error: Value "DLLFile" already exists

### ISSUE THREAD

**Issue by Prototrintro** [X-Hax/SA-Mod-Manager#131]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.8
	Current Game: Sonic Adventure 2
	Game Directory: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2
	Manager Location: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\
	Running as Admin: False
	Mod Loader Version (Hash): 7e472d7453bf152c91e49398ec0f867b4c689702
```

```
Exception Information:
	Exception: INI File error: Value "DLLFile" already exists in group "".
line 7
	Source: SAModManager
	In Function: System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,System.String]] Load(System.String[])
	StackTrace:    at SAModManager.Ini.IniFile.Load(String[] data)
	   at SAModManager.Ini.IniFile.Load(String filename)
	   at SAModManager.Ini.IniSerializer.Deserialize[T](String filename)
	   at SAModManager.MainWindow.LoadModList()
	   at SAModManager.MainWindow.Load(Boolean newSetup)
	   at SAModManager.MainWindow.MainWindowManager_Loaded(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
	InnerException: System.ArgumentException: An item with the same key has already been added. Key: DLLFile
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SAModManager.Ini.IniFile.Load(String[] data)
```

**Comment by Prototrintro** [comment]
when i was downloading a mod it came up with this and idk how to fix it

**Comment by Sora-yx** [comment]
One of your mod has its mod.ini wrong, most likely the goose mod since it is known for that, the author never fixed it.
