### ISSUE TITLE
[Error Report]: Crash when Saving on First boot

### ISSUE THREAD

**Issue by Blimby0** [X-Hax/SA-Mod-Manager#152]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.9
	First Boot: True
	Current Game: Sonic Adventure 2
	Game Directory: 
	Manager Location: C:\Users\Braden\Downloads\SA2ModLoader\
	Running as Admin: False
```

```
Exception Information:
	Type: ArgumentException
	Exception: The path is empty. (Parameter 'path')
	Source: System.Private.CoreLib
	In Function: System.String GetFullPath(System.String)
	StackTrace:    at System.IO.Path.GetFullPath(String path)
	   at SAModManager.MainWindow.SaveSA2Settings()
	   at SAModManager.MainWindow.Save()
	   at SAModManager.MainWindow.ComboGameSelection_SelectionChanged(Object sender, SelectionChangedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by ItsEasyActually** [comment]
More info needed. 

What were you doing that caused this crash? It looks like you have your mod manager installed in your downloads folder and were attempting to switch to SA2 but it failed. This indicates there's some issue with your settings folder or with the Mod Manager picking up SA2, but without more information I can't really help with the issue.

Useful info would be the actual install location of the SA Mod Manager, if you used the upgrade path from the SA2 Mod Manager or if you install the SA Mod Manager independently, and the current state of your SA2 install. Additionally, if you can check your `Users/[username]/AppData/Local/SAManager` folder and see if it has an SA2 folder with some files inside, that would be great.

**Comment by Sora-yx** [comment]
Looks like the crash happened because the game path was empty, this will be fixed in the next update.
