### ISSUE TITLE
[Error Report]:

### ISSUE THREAD

**Issue by KevinPecci** [X-Hax/SA-Mod-Manager#154]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.9
	Current Game: Sonic Adventure 2
	Game Directory: D:\SteamLibrary\steamapps\common\Sonic Adventure 2
	Manager Location: D:\SteamLibrary\steamapps\common\Sonic Adventure 2\mods\release_x64_a3a8a\
	Running as Admin: False
	Mod Loader Version (Hash): 16e963f9ef335dd521e115ef59f5a79ff6d957c4
```

```
Exception Information:
	Type: Win32Exception
	Exception: An error occurred trying to start process 'D:\SteamLibrary\steamapps\common\Sonic Adventure 2\sonic2app.exe' with working directory 'D:\SteamLibrary\steamapps\common\Sonic Adventure 2'. The system cannot find the file specified.
	Source: System.Diagnostics.Process
	In Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
	StackTrace:    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
	   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
	   at SAModManager.MainWindow.StartGame()
	   at SAModManager.MainWindow.SaveAndPlayButton_Click(Object sender, RoutedEventArgs e)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
	   at System.Windows.Controls.Button.OnClick()
	   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
	   at System.Windows.Input.InputManager.ProcessStagingArea()
	   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
	   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
	   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by ItsEasyActually** [comment]
Your SA2 executable is missing or potentially renamed.
