### ISSUE TITLE
[Error Report]:

### ISSUE THREAD

**Issue by RACKET77** [X-Hax/SA-Mod-Manager#165]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.10
	First Boot: True
	Current Game: Sonic Adventure DX
	Game Directory: C:\\Program Files (x86)\\Steam\steamapps\common\Sonic Adventure DX
	Manager Location: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure DX\
	Running as Admin: False
	Mod Loader Version (Hash): 81582f847e3cefed2f50365655f38a4da934d7b8
```

```
Exception Information:
	Type: ArgumentException
	Exception: An item with the same key has already been added. Key: nput-mod
	Source: System.Private.CoreLib
	In Function: Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
	StackTrace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
	   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
	   at SAModManager.MainWindow.LoadModList()
	   at SAModManager.MainWindow.Load(Boolean newSetup)
	   at SAModManager.MainWindow.MainWindowManager_Loaded(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by Sora-yx** [comment]
As the error mentions, you have a mod with a duplicate key somewhere, find it and your issue will be fixed.

**Comment by PiKeyAr** [comment]
`nput-mod`?
