### ISSUE TITLE
[Error Report]: I keep getting this error on every launch

### ISSUE THREAD

**Issue by PlatOmegax** [X-Hax/SA-Mod-Manager#173]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.9
	Current Game: Sonic Adventure 2
	Game Directory: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2
	Manager Location: C:\Users\kevin\OneDrive\Desktop\Mod backups\Sonic adventure Mod Manager\
	Running as Admin: False
	Mod Loader Version (Hash): 3da2f0c67370d0019c1163def519f59bb0335cb5
```

```
Exception Information:
	Exception: Failed to create Profile Directory.
	Source: SAModManager
	In Function: Void Serialize(System.String)
	StackTrace:    at SAModManager.Profile.Profiles.Serialize(String path)
	   at SAModManager.Profile.ProfileManager.SaveProfiles()
	   at SAModManager.MainWindow.Save()
	   at SAModManager.MainWindow.comboProfile_SelectionChanged(Object sender, SelectionChangedEventArgs e)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
	   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
	   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
	   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
	   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
	   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
	   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
	   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
	   at System.Windows.Data.BindingOperations.SetBinding(DependencyObject target, DependencyProperty dp, BindingBase binding)
	   at SAModManager.MainWindow.SetManagerBindings()
	   at SAModManager.MainWindow.SetBindings()
	   at SAModManager.MainWindow.MainWindowManager_Loaded(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by Sora-yx** [comment]
Well, first of all your Mod Manager isn't up to date, you should always report issue with the last version installed.
Second, you shouldn't store the Mod Manager in a OneDrive folder since it does a lot of read and write operations.
If after all of that the issue persist, please let us know.

**Comment by PlatOmegax** [comment]
It's done it with 1.2.10 as well so I tried a different version. Where do I put the exe btw it's always worked in a folder on my desktop so just curious where am I actually supposed to put it

**Comment by PlatOmegax** [comment]
I tried putting the file in the game folders in steam and it's still giving me the amrita error on 1.2.10

**Comment by Sora-yx** [comment]
Can you run it as admin and see if the issue persist?

**Comment by PlatOmegax** [comment]
It does both in the unzipped folder and game folder

**Comment by PlatOmegax** [comment]
Any update on what I should try as it seems others are having a similar issue

**Comment by PiKeyAr** [comment]
Others, like who? I've personally never experienced this error on any of my systems, and I've not seen reports of this issue outside this thread.


The handling of this particular error in the Mod Manager's code does not produce details on the exact exception that occurred, but the error suggests there could've been a problem trying to write a file or folder. It could be that Windows is preventing the Mod Manager from creating folders or writing files.

**Comment by PlatOmegax** [comment]
Is there a way I can uninstall the mod loader and start over?

**Comment by Sora-yx** [comment]
Delete `SAModManager.exe` then delete the folder `SAManager` in Appdata -> Local.

**Comment by PlatOmegax** [comment]
Thank you so much I apologize for the trouble that fixed it
