### ISSUE TITLE
Crash with GB Mod Updates

### ISSUE THREAD

**Issue by DoomisEternal** [X-Hax/SA-Mod-Manager#176]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.10
	Current Game: Sonic Adventure DX
	Game Directory: D:\SteamLibrary\steamapps\common\Sonic Adventure DX
	Manager Location: D:\SteamLibrary\steamapps\common\Sonic Adventure DX\
	Running as Admin: False
	Mod Loader Version (Hash): c6f3082909276cc4a13bda7b7b8b4b38c83a1e23
```

```
Exception Information:
	Type: NullReferenceException
	Exception: Object reference not set to an instance of an object.
	Source: SAModManager
	In Function: Void MoveNext()
	StackTrace:    at SAModManager.Updater.ModUpdater.GetGameBananaReleases(ModInfo mod, String modsFolder, String folder, List`1 errors, String basePath)
	   at SAModManager.Updater.ModUpdater.GetModUpdates(String modsFolder, CancellationToken cancellationToken, String baseFolder)
	   at SAModManager.MainWindow.UpdateChecker_DoWork()
	   at SAModManager.MainWindow.ExecuteModsUpdateCheck()
```

**Comment by Sora-yx** [comment]
Should be fixed with the last update, if that happens again feel free to re open.
