### ISSUE TITLE
[Error Report]: Crash with game swap with patches for the wrong game 

### ISSUE THREAD

**Issue by ClassicSonicFan1** [X-Hax/SA-Mod-Manager#179]
## Exception Report
```
SAMM Information:
	Manager Version: 1.2.10
	Current Game: Sonic Adventure 2
	Game Directory: C:\Users\ikiro\Desktop\SA MODED
	Manager Location: C:\Users\ikiro\Desktop\SA MODED\
	Running as Admin: False
	Mod Loader Version (Hash): e74e1cdbe0fb9501867eda6dd74a177476d736f2
```

```
Exception Information:
	Type: InvalidOperationException
	Exception: Property HRTFSound not found or read-only.
	Source: SAModManager
	In Function: Void SavePatches(System.Object ByRef)
	StackTrace:    at SAModManager.Controls.SA2.GameConfig.SavePatches(Object& input)
	   at SAModManager.MainWindow.SaveSA2Settings()
	   at SAModManager.MainWindow.Save()
	   at SAModManager.MainWindow.ComboGameSelection_SelectionChanged(Object sender, SelectionChangedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by Sora-yx** [comment]
That sounds like you don't have the patchs downloaded, is your patch list empty? If so, click on "uninstall loader" then "install loader".

**Comment by sonickid1816** [comment]
I think my error report was the same. Try reinstalling all of your SA2 mods and see if that helps.

**Comment by ItsEasyActually** [comment]
Please update your Manager to the latest version as some changes should prevent this error from continuing to occur. You may need to do a fresh install of the loaders for both games. If this issue persists, feel free to reopen this issue.
