### ISSUE TITLE
[Error Report]: Ukrainian language doesn't work

### ISSUE THREAD

**Issue by Semechko1** [X-Hax/SA-Mod-Manager#185]
I keep getting this error message whenever I switch language to Ukrainian. Even is file is present (Languages/uk-UA.xaml) and correctly referenced in Languages/languages.xaml, I still but this even after several updates. 

To trigger it, you just need to switch to Ukrainian in the settings.

## Exception Report
```
SAMM Information:
	Manager Version: 1.2.10
	Current Game: Sonic Adventure DX
	Game Directory: D:\SteamLibrary\steamapps\common\Sonic Adventure DX
	Manager Location: D:\SteamLibrary\steamapps\common\Sonic Adventure DX\
	Running as Admin: False
	Mod Loader Version (Hash): e8bf205f24c069f5ce5569b01e3c3a4a3c1fc7aa
```

```
Exception Information:
	Type: IOException
	Exception: Cannot locate resource 'languages/uk-ua.xaml'.
	Source: PresentationFramework
	In Function: System.IO.Stream GetStreamCore(System.IO.FileMode, System.IO.FileAccess)
	StackTrace:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
	   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
	   at MS.Internal.IO.Packaging.PackagePartExtensions.GetSeekableStream(PackagePart packPart, FileMode mode, FileAccess access)
	   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
	   at System.IO.Packaging.PackWebResponse.get_ContentType()
	   at MS.Internal.WpfWebRequestHelper.GetContentType(WebResponse response)
	   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
	   at System.Windows.ResourceDictionary.set_Source(Uri value)
	   at SAModManager.App.SwitchLanguage()
	   at SAModManager.MainWindow.comboLanguage_SelectionChanged(Object sender, SelectionChangedEventArgs e)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
	   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
	   at System.Windows.Controls.ComboBox.NotifyComboBoxItemMouseUp(ComboBoxItem comboBoxItem)
	   at System.Windows.Controls.ComboBoxItem.OnMouseLeftButtonUp(MouseButtonEventArgs e)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
	   at System.Windows.Input.InputManager.ProcessStagingArea()
	   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
	   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
	   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

the Manager.json file (I guess it didn't update settings after crash, but it happened to me once):
```
{
  "SettingsVersion": 1,
  "CurrentSetGame": 1,
  "Theme": 0,
  "Language": 0,
  "ModAuthor": "Semka",
  "EnableDeveloperMode": false,
  "KeepManagerOpen": true,
  "UpdateSettings": {
    "EnableManagerBootCheck": true,
    "EnableModsBootCheck": false,
    "EnableLoaderBootCheck": true,
    "UpdateTimeOutCD": 133673970293625966,
    "UpdateCheckCount": 2
  },
  "gamesInstalled": [
    1,
    2
  ]
}
```
Would be cool if manager automatically switched to English if any similar (language) error happens. That way user could still use it...

**Comment by Sora-yx** [comment]
That's known and fixed on the dev build.

**Comment by Sora-yx** [comment]
On this topic, I just re tested on the dev build and got two new errors from duplicate key in the xaml file, please be careful before submiting changes as well, duplicate key will crash no matter what and I can't add a failsafe for those.

**Comment by Semechko1** [comment]
...duplicate key? where was it?

**Comment by Sora-yx** [comment]
https://github.com/X-Hax/SA-Mod-Manager/commit/d8cddfa9583cd4b5a580489052425e337eafef16

**Comment by Semechko1** [comment]
ohh, must have been a merging issue (managing and adding new strings in Notepad++ can be tricky sometimes). Thanks!
