### ISSUE TITLE
[Error Report]: Malformed update information

### ISSUE THREAD

**Issue by Xenoeatssalad** [X-Hax/SA-Mod-Manager#201]
idk what happen i opened the mod manager and i got this
```
SAMM Information:
	Manager Version: 1.2.11
	Current Game: Sonic Adventure 2
	Game Directory: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2
	Manager Location: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure DX\
	Running as Admin: False
	Mod Loader Version (Hash): 43113120a75480555224f72df7c717237e736f35
```

```
Exception Information:
	Type: UriFormatException
	Exception: Invalid URI: The hostname could not be parsed.
	Source: System.Private.Uri
	In Function: Void CreateThis(System.String, Boolean, System.UriKind, System.UriCreationOptions ByRef)
	StackTrace:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
	   at System.Uri..ctor(String uriString)
	   at SAModManager.Updater.ModUpdater.CheckModularVersion(ModInfo mod, String modsFolder, String folder, List`1 localManifest, HttpClient client, List`1 errors, String basePath)
	   at SAModManager.Updater.ModUpdater.GetModUpdates(String modsFolder, CancellationToken cancellationToken, String baseFolder)
	   at SAModManager.MainWindow.UpdateChecker_DoWork()
	   at SAModManager.MainWindow.ExecuteModsUpdateCheck()
```

**Comment by ItsEasyActually** [comment]
It would appear one of your mods may have a malformed update information in it. You'll have to find which mod it is on your own. If you do, please let us know, so we can add a proper exception for this.
