### ISSUE TITLE
[Error Report]: the manager has encountered and error

### ISSUE THREAD

**Issue by SonicRingz** [X-Hax/SA-Mod-Manager#233]
## Exception Report
```
SAMM Information:
	Manager Version: 1.3.1
	Current Game: Sonic Adventure 2
	Game Directory: D:\SteamLibrary\steamapps\common\Sonic Adventure 2
	Manager Location: D:\SteamLibrary\steamapps\common\Sonic Adventure 2\
	Running as Admin: False
	Mod Loader Version (Hash): 98c991e7a7bf185651ea7ff655976d0c891682d8
```

```
Exception Information:
	Type: UriFormatException
	Exception: Invalid URI: The hostname could not be parsed.
	Source: System.Private.Uri
	In Function: Void CreateThis(System.String, Boolean, System.UriKind, System.UriCreationOptions ByRef)
	StackTrace:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
	   at System.Uri..ctor(String uriString)
	   at SAModManager.Updater.ModUpdater.CheckModularVersion(ModInfo mod, String modsFolder, String folder, List`1 localManifest, HttpClient client, List`1 errors, String basePath)
	   at SAModManager.Updater.ModUpdater.GetModUpdates(String modsFolder, CancellationToken cancellationToken, String baseFolder)
	   at SAModManager.MainWindow.UpdateChecker_DoWork()
	   at SAModManager.MainWindow.ExecuteModsUpdateCheck()
```

how can i fix this from popping up everytime?

**Comment by SonicRingz** [comment]
"super shadow chao" had a smiley face as an update link. lol
