### ISSUE TITLE
[Error Report]:Error updating SA Mod Manager, reports the release is a virus

### ISSUE THREAD

**Issue by DarkOverord** [X-Hax/SA-Mod-Manager#234]
Error occurs on accepting the v1.3.1update download via the app. The details reports below but I think this might be the more pertinent points:

![Release is a Virus](https://github.com/user-attachments/assets/d67c6ea5-c78c-464a-8022-1d5ec773638f)

Windows defender is also reporting the below:

![Release is a Virus - Windows Defender](https://github.com/user-attachments/assets/60af7ffc-c38a-4617-8600-d012862d2a0b)

## Exception Report
```
SAMM Information:
	Manager Version: 1.2.11
	Current Game: Sonic Adventure 2
	Game Directory: G:\Steam\steamapps\common\Sonic Adventure 2
	Manager Location: G:\Archipelago\Sonic Adventure\
	Running as Admin: False
	Mod Loader Version (Hash): d90d7879b4e59a0b1d93a87433e44e8ac4839816
```

```
Exception Information:
	Exception: Couldn't find new version of the manager

	Source: SAModManager
	In Function: Void MoveNext()
	StackTrace:    at SAModManager.Updater.ManagerUpdate.DownloadManagerCompleted(String tempFolderPath, String fileName)
	   at SAModManager.App.<>c__DisplayClass52_0.<<PerformUpdateManagerCheck>b__0>d.MoveNext()
	--- End of stack trace from previous location ---
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

```
{
  "SettingsVersion": 1,
  "CurrentSetGame": 2,
  "Theme": 0,
  "Language": 0,
  "ModAuthor": "",
  "EnableDeveloperMode": false,
  "KeepManagerOpen": true,
  "UpdateSettings": {
    "EnableManagerBootCheck": true,
    "EnableModsBootCheck": true,
    "EnableLoaderBootCheck": true,
    "UpdateTimeOutCD": 0,
    "UpdateCheckCount": 0
  },
  "gamesInstalled": [
    1,
    2
  ],
  "managerWidth": 650,
  "managerHeight": 700
}
```
```
{
  "SettingsVersion": 2,
  "Graphics": {
    "SelectedScreen": 1,
    "HorizontalResolution": 1600,
    "VerticalResolution": 900,
    "EnablePauseOnInactive": false,
    "CustomWindowWidth": 640,
    "CustomWindowHeight": 480,
    "EnableKeepResolutionRatio": false,
    "EnableResizableWindow": false,
    "ScreenMode": 0,
    "StretchToWindow": false,
    "GameTextLanguage": 0,
    "SkipIntro": false,
    "RefreshRate": 60,
    "DisableBorderImage": false
  },
  "TestSpawn": {
    "UseCharacter": false,
    "UsePlayer2": false,
    "UseLevel": false,
    "UseEvent": false,
    "UseSave": false,
    "LevelIndex": -1,
    "MissionIndex": 0,
    "CharacterIndex": -1,
    "Player2Index": -1,
    "EventIndex": -1,
    "SaveIndex": -1,
    "GameTextLanguage": 0,
    "GameVoiceLanguage": 1,
    "UseManual": false,
    "UsePosition": false,
    "XPosition": 0,
    "YPosition": 0,
    "ZPosition": 0,
    "Rotation": 0
  },
  "Patches": {
    "FramerateLimiter": true,
    "DisableExitPrompt": true,
    "SyncLoad": true,
    "ExtendVertexBuffer": true,
    "EnvMapFix": true,
    "ScreenFadeFix": true,
    "CECarFix": true,
    "ParticlesFix": true
  },
  "DebugSettings": {
    "EnableDebugConsole": false,
    "EnableDebugScreen": false,
    "EnableDebugFile": false,
    "EnableDebugCrashLog": true,
    "EnableShowConsole": null
  },
  "GamePath": "G:\\Steam\\steamapps\\common\\Sonic Adventure 2",
  "EnabledMods": [
    "SA2 Render Fix",
    "Minimal Pickup Fix",
    "Reworked Afterimages",
    "Rouge\u0027s eye animation Fix",
    "SA2 Volume Controls",
    "Tikal Stance Fix",
    "Wishes Are Eternal Remade",
    "HD GUI_ SA2 Edition",
    "SA1 Style Life Icons",
    "Menu Overhaul",
    "Enhanced Chao World",
    "GCNGardenTitles",
    "CWE Mods - Darky Hats (Wave 1)",
    "Chao World Extended v9.4",
    "Chao Camera",
    "SA2B_Archipelago",
    "Enhanced City Escape"
  ],
  "EnabledCodes": []
}
```

**Comment by reckdave** [comment]
this is also happening to me

**Comment by kawaiikaorichan** [comment]
Also happened to me.
Solution: Be fast, literally. As soon as Windows defender detects the file as a virus, click on the notification, display the options in the "Severe" word, and in actions select "Allow". Close the Manager and try again, it updates normally now.

**Comment by kawaiikaorichan** [comment]
I contribute to the project with translations, because of that I have access to the code, so I can confirm it doesn't have any virus, it's a false positive.

**Comment by ShadowTheLight** [comment]
> I contribute to the project with translations, because of that I have access to the code, so I can confirm it doesn't have any virus, it's a false positive.

that's good to hear, ill add an exception then. hopefully future versions will find a way to make this not required tho 🤞

**Comment by ItsEasyActually** [comment]
We have basically zero control over Windows Defender picking it up unfortunately, same goes for any anti-virus. Our programs are open source, and we're not going to be putting malicious software on anyone's computer. It's on the user to decide if they trust that statement (or want to verify themselves) if a false positive is found.
