### ISSUE TITLE
[Error Report]: Mod Manager Won't Recognize EXE file

### ISSUE THREAD

**Issue by soupallergy** [X-Hax/SA-Mod-Manager#246]
Not sure why, as they have the same name, but the mod loader will not recognize sonic2app.exe in the directory. I'm sure that in each mod .ini the .exe it's pointing to is sonic2app.exe.

## Exception Report
```
SAMM Information:
	Manager Version: 1.3.1
	Current Game: Sonic Adventure 2
	Game Directory: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2
	Manager Location: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\
	Running as Admin: False
	Mod Loader Version (Hash): a1f55665828ffad343deaca1bce89bb2389cf311
```

```
Exception Information:
	Type: Win32Exception
	Exception: An error occurred trying to start process 'C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\mods\ChaoWorldExtended\HDTexture\sonic2app.exe' with working directory 'C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2'. The system cannot find the file specified.
	Source: System.Diagnostics.Process
	In Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
	StackTrace:    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
	   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
	   at SAModManager.MainWindow.StartGame()
	   at SAModManager.MainWindow.SaveAndPlayButton_Click(Object sender, RoutedEventArgs e)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
	   at System.Windows.Controls.Button.OnClick()
	   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
	   at System.Windows.Input.InputManager.ProcessStagingArea()
	   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
	   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by ItsEasyActually** [comment]
As stated, this is happening because, somehow, you have the program trying to launch an executable that is in a sub folder of a mod that doesn't use a custom executable. This implies either you installed a mod that incorrectly sets up a custom executable path despite there not being an executable in that location for it to launch. 

This isn't an issue with the Manager, so I'm going to close this. If you happen to figure out what mod did this (assuming you didn't make it), please report it to the mod author so they fix it.

**Comment by PiKeyAr** [comment]
IMO there's still potential to improve how the Manager deals with things like this. Unhandled exceptions shouldn't happen even if the mod contains missing or invalid metadata. The Manager could check if the file exists before attempting to execute it, and let the user know the mod has invalid data if the file doesn't exist. This principle should apply to the entire program: things like fetching updates from GameBanana etc. that can potentially result in an error should be handled properly instead of making the program crash, everything that could be null should be wrapped in a null check etc.


The reason I think this should be done is that the Manager is often used by inexperienced users who barely understand what they're doing, and with the lack of proper error handling every error they get ends up on this tracker, regardless of whether it's a user's fault or not.
