### ISSUE TITLE
[Error Report]:

### ISSUE THREAD

**Issue by Shines113** [X-Hax/SA-Mod-Manager#247]
## Exception Report
```
SAMM Information:
	Manager Version: 1.3.1
	Current Game: Sonic Adventure 2
	Game Directory: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2
	Manager Location: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\
	Running as Admin: False
	Mod Loader Version (Hash): a1f55665828ffad343deaca1bce89bb2389cf311
```

```
Exception Information:
	Type: NullReferenceException
	Exception: Object reference not set to an instance of an object.
	Source: SAModManager
	In Function: Void MoveNext()
	StackTrace:    at SAModManager.Updater.ModUpdater.GetGameBananaReleases(ModInfo mod, String modsFolder, String folder, List`1 errors, String basePath)
	   at SAModManager.Updater.ModUpdater.GetModUpdates(String modsFolder, CancellationToken cancellationToken, String baseFolder)
	   at SAModManager.MainWindow.UpdateChecker_DoWork()
	   at SAModManager.MainWindow.ExecuteModsUpdateCheck()
```

```
{
  "SettingsVersion": 1,
  "CurrentSetGame": 2,
  "Theme": 0,
  "Language": 0,
  "ModAuthor": "",
  "EnableDeveloperMode": false,
  "KeepManagerOpen": true,
  "UpdateSettings": {
    "EnableManagerBootCheck": true,
    "EnableModsBootCheck": true,
    "EnableLoaderBootCheck": true,
    "UpdateTimeOutCD": 0,
    "UpdateCheckCount": 1
  },
  "gamesInstalled": [
    2,
    1
  ],
  "managerWidth": 650,
  "managerHeight": 725,
  "KeepModOrder": false
}
```
```
{
  "SettingsVersion": 2,
  "Graphics": {
    "SelectedScreen": 1,
    "HorizontalResolution": 1920,
    "VerticalResolution": 1080,
    "EnablePauseOnInactive": true,
    "CustomWindowWidth": 640,
    "CustomWindowHeight": 480,
    "EnableKeepResolutionRatio": false,
    "EnableResizableWindow": false,
    "ScreenMode": 1,
    "StretchToWindow": false,
    "GameTextLanguage": 0,
    "SkipIntro": false,
    "RefreshRate": 60,
    "DisableBorderImage": false
  },
  "TestSpawn": {
    "UseCharacter": false,
    "UsePlayer2": false,
    "UseLevel": false,
    "UseEvent": false,
    "UseSave": false,
    "LevelIndex": -1,
    "MissionIndex": 0,
    "CharacterIndex": -1,
    "Player2Index": -1,
    "EventIndex": -1,
    "SaveIndex": -1,
    "GameTextLanguage": 0,
    "GameVoiceLanguage": 1,
    "UseManual": false,
    "UsePosition": false,
    "XPosition": 0,
    "YPosition": 0,
    "ZPosition": 0,
    "Rotation": 0
  },
  "Patches": {
    "FramerateLimiter": true,
    "DisableExitPrompt": true,
    "SyncLoad": true,
    "ExtendVertexBuffer": true,
    "EnvMapFix": true,
    "ScreenFadeFix": true,
    "CECarFix": true,
    "ParticlesFix": true
  },
  "DebugSettings": {
    "EnableDebugConsole": false,
    "EnableDebugScreen": false,
    "EnableDebugFile": false,
    "EnableDebugCrashLog": true,
    "EnableShowConsole": null
  },
  "GamePath": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Sonic Adventure 2",
  "EnabledMods": [],
  "EnabledCodes": [],
  "ModsList": [
    "Amy New Tricks",
    "Better Miles (Tails Gameplay Overhaul)",
    "Chao World Extended v9.5",
    "Character Select PLUS",
    "Cutscene Revamp",
    "Enhanced Chao World",
    "HedgePanel - Sonic \u002B Shadow Tweaks",
    "Knuckles_ New Tricks",
    "Mecha Sonic",
    "No Battle",
    "SA2 Render Fix",
    "SA2 Volume Controls",
    "Sonic_ New Tricks",
    "SA2 Super Sonic _ Shadow"
  ]
}
```

**Comment by Shines113** [comment]
User error. unsure what caused game to not launch, but in performing a clean and manual install through the manager, problem resolved.
