### ISSUE TITLE
[Error Report]: "Manager Crashed" upon launch each time

### ISSUE THREAD

**Issue by skmistress** [X-Hax/SA-Mod-Manager#54]
Every time I launch the manager, I get the "Manager Crashed" followed by this log. I don't remember doing anything to cause this. 

## Exception Report
```
SAMM Information:	Manager Version: 1.1.2
	Current Game: Sonic Adventure DX
	Game Directory: 
	Mod Loader Version (Hash): 7f9670822ba35a2916cbc31f4ecb290123e702a8
```

```
Exception Information:
	Type: NullReferenceException
	Exception: Object reference not set to an instance of an object.
	Source: SAModManager
	In Function: Void ValidateProfiles()
	StackTrace:    at SAModManager.Configuration.Profiles.ValidateProfiles()
	   at SAModManager.MainWindow.Load(Boolean newSetup)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by Sora-yx** [comment]
If you go in **AppData -> Local** you should find a folder called **"SAManager"**, delete it, that should reset the settings and fix your issue.

**Comment by skmistress** [comment]
> If you go in **AppData -> Local** you should find a folder called **"SAManager"**, delete it, that should reset the settings and fix your issue.

Oh, that did work! Thank you!
