### ISSUE TITLE
[Error Report]: One Click Install Crash

### ISSUE THREAD

**Issue by BiffMcGheek** [X-Hax/SA-Mod-Manager#76]
## Exception Report
```
SAMM Information:
	Manager Version: 1.1.6
	Current Game: Sonic Adventure DX
	Game Directory: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure DX
	Manager Location: D:\Games\ModStuff\Sonic\SADX\
	Running as Admin: False
	Mod Loader Version (Hash): 9140fcf9393464a03b69a1e9a83f61b2594f5d54
```

```
Exception Information:
	Type: ArgumentNullException
	Exception: Value cannot be null. (Parameter 'path1')
	Source: System.Private.CoreLib
	In Function: Void Throw(System.String)
	StackTrace:    at System.ArgumentNullException.Throw(String paramName)
	   at System.IO.Path.Combine(String path1, String path2)
	   at SAModManager.OneClickInstall.ButtonDownload_Click(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Window.ShowHelper(Object booleanBox)
	   at System.Windows.Window.Show()
	   at System.Windows.Window.ShowDialog()
	   at SAModManager.OneClickInstall.HandleUri(String uri)
	   at SAModManager.OneClickInstall.UriQueueOnUriEnqueued(Object sender, OnUriEnqueuedArgs args)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

```
{
  "SettingsVersion": 1,
  "CurrentSetGame": 1,
  "Theme": 0,
  "Language": 0,
  "ModAuthor": "",
  "EnableDeveloperMode": false,
  "KeepManagerOpen": true,
  "UpdateSettings": {
    "EnableManagerBootCheck": true,
    "EnableModsBootCheck": true,
    "EnableLoaderBootCheck": true,
    "UpdateTimeOutCD": 133534897686282941,
    "UpdateCheckCount": 2
  }
}
```
```
{
  "SettingsVersion": 1,
  "Graphics": {
    "SelectedScreen": 2,
    "HorizontalResolution": 2560,
    "VerticalResolution": 1440,
    "Enable43ResolutionRatio": false,
    "EnableVsync": true,
    "EnablePauseOnInactive": true,
    "EnableBorderless": true,
    "EnableScreenScaling": true,
    "EnableCustomWindow": false,
    "CustomWindowWidth": 640,
    "CustomWindowHeight": 480,
    "EnableKeepResolutionRatio": false,
    "EnableResizableWindow": false,
    "FillModeBackground": 2,
    "FillModeFMV": 1,
    "ModeTextureFiltering": 0,
    "ModeUIFiltering": 0,
    "EnableUIScaling": true,
    "EnableForcedMipmapping": true,
    "EnableForcedTextureFilter": true
  },
  "Controller": {
    "EnabledInputMod": true
  },
  "Sound": {
    "EnableBassMusic": true,
    "EnableBassSFX": true,
    "SEVolume": 100
  },
  "TestSpawn": {
    "UseCharacter": false,
    "UseLevel": false,
    "UseEvent": false,
    "UseGameMode": false,
    "UseSave": false,
    "LevelIndex": -1,
    "ActIndex": 0,
    "CharacterIndex": -1,
    "EventIndex": -1,
    "GameModeIndex": -1,
    "SaveIndex": -1,
    "GameTextLanguage": 1,
    "GameVoiceLanguage": 1,
    "UseManual": false,
    "UsePosition": false,
    "XPosition": 0,
    "YPosition": 0,
    "ZPosition": 0,
    "Rotation": 0
  },
  "Patches": {
    "HRTFSound": true,
    "KeepCamSettings": true,
    "FixVertexColorRendering": true,
    "MaterialColorFix": true,
    "NodeLimit": true,
    "FOVFix": true,
    "SkyChaseResolutionFix": true,
    "Chaos2CrashFix": true,
    "ChunkSpecularFix": true,
    "E102NGonFix": true,
    "ChaoPanelFix": true,
    "PixelOffSetFix": true,
    "LightFix": true,
    "KillGBIX": true,
    "DisableCDCheck": false,
    "ExtendedSaveSupport": true
  },
  "DebugSettings": {
    "EnableDebugConsole": false,
    "EnableDebugScreen": false,
    "EnableDebugFile": false,
    "EnableDebugCrashLog": true,
    "EnableShowConsole": null
  },
  "GamePath": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Sonic Adventure DX",
  "EnabledMods": [
    "DreamcastConversion",
    "SA1_Chars",
    "sadx-dc-lighting",
    "SoundOverhaul",
    "sadx-input-mod",
    "Better Dreamcast Sonic",
    "AI HD FMVs",
    "(DC_DX) ESRGAN-AI HD Textures",
    "DLC",
    "smooth-cam",
    "sadx-frame-limit",
    "sadx-onion-blur",
    "idle-chatter",
    "SteamAchievements",
    "sadx-style-water",
    "TrainDaytime",
    "sadx-super-sonic",
    "HD_DCStyle",
    "16_9_unstretched Flashbacks",
    "DiscordSADX",
    "HD Rings"
  ],
  "EnabledCodes": [
    "Can Always Skip Credits"
  ]
}
```

**Comment by Sora-yx** [comment]
If the issue persist with the last update, please re open and share what mod causes it.
