### ISSUE TITLE
[Error Report] Crash with XML Config

### ISSUE THREAD

**Issue by namenamenam** [X-Hax/SA-Mod-Manager#84]
## Exception Report
```
SAMM Information:
	Manager Version: 1.1.6
	Current Game: Sonic Adventure DX
	Game Directory: R:\PortableApps\SONICADVENTUREDX
	Manager Location: R:\PortableApps\SONICADVENTUREDX\
	Running as Admin: True
	Mod Loader Version (Hash): 61075bad5ee2f828665c96f64868fd5cd28b9461
```

```
Exception Information:
	Type: FormatException
	Exception: The input string '-2.7755575615628914E-17' was not in a correct format.
	Source: System.Private.CoreLib
	In Function: Void ThrowOverflowOrFormatException(ParsingStatus, System.ReadOnlySpan`1[System.Char], System.TypeCode)
	StackTrace:    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
	   at System.Decimal.Parse(String s, IFormatProvider provider)
	   at SAModManager.Common.CustomPropertyStore.GetConfigValue()
	   at SAModManager.FormBuilder.CreateNumericBox(ConfigSchemaProperty property, CustomPropertyStore storeInfo, DataType dataType)
	   at SAModManager.FormBuilder.ConfigCreateItem(ConfigSchemaProperty elem, ConfigSettings config, CustomPropertyStore storeInfo)
	   at SAModManager.FormBuilder.ConfigBuild(ConfigSettings& config)
	   at SAModManager.Common.ModConfig..ctor(String Modname, String path, Boolean reset)
	   at SAModManager.MainWindow.InitModConfig()
	   at SAModManager.MainWindow.ConfigureModBtn_Click(Object sender, RoutedEventArgs e)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
	   at System.Windows.Controls.Button.OnClick()
	   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
	   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
	   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
	   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
	   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
	   at System.Windows.Input.InputManager.ProcessStagingArea()
	   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
	   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
	   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at SAModManager.App.Main()
```

**Comment by ItsEasyActually** [comment]
This error looks like it's due to a config.ini file having a value that couldn't be parsed properly by the Decimal class. 

Can you explain what you were doing when this error occurred? Namely if you had modified the config file in the manager before this occurred or not.

**Comment by ItsEasyActually** [comment]
I've made some changes in c9a7765 that should prevent this issue from happening.
