### ISSUE TITLE
[Error Report]:After Installing BetterSADX SA Mod Loader crashes upon saving/updating

### ISSUE THREAD

**Issue by D-Star322** [X-Hax/SA-Mod-Manager#94]
After Installing BetterSADX My SA Mod Loader would allways crash upon saving or updating with the Exception of not finding some property called CrashGuard. It worked just fine before installing BetterSADX and even after I uninstall it the crash would still happen.

## Exception Report
```
SAMM Information:
	Manager Version: 1.1.6
	Current Game: Sonic Adventure DX
	Game Directory: D:\Games\steam\steamapps\common\Sonic Adventure DX
	Manager Location: D:\Games\steam\steamapps\common\Sonic Adventure DX\
	Running as Admin: True
	Mod Loader Version (Hash): 9f3674ef6b90deb5cce44b393157cc24c42173c6
```

```
Exception Information:
	Type: InvalidOperationException
	Exception: Property CrashGuard not found or read-only.
	Source: SAModManager
	In Function: Void SavePatches(System.Object ByRef)
	StackTrace:    at SAModManager.Elements.SADX.GameConfig.SavePatches(Object& input)
	   at SAModManager.MainWindow.SaveSADXSettings()
	   at SAModManager.MainWindow.Save()
	   at SAModManager.MainWindow.ResultPickGame(String path)
	   at SAModManager.MainWindow.btnBrowseGameDir_Click(Object sender, RoutedEventArgs e)
	   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
	   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
	   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
	   at System.Windows.Threading.Dispatcher.Run()
	   at System.Windows.Application.RunDispatcher(Object ignore)
	   at System.Windows.Application.RunInternal(Window window)
	   at System.Windows.Application.Run()
	   at SAModManager.App.Main()
```

**Comment by Sora-yx** [comment]
1. Your Manager isn't up to date, we are currently on 1.2.1 this is most likely the reason of your issue.
2. BetterSADX is outdated and shouldn't be used [SADX Mod Installer](https://sadxmodinstaller.unreliable.network/) is the way to go.
